fix: 更新工作流中指定的 Dart SDK 版本
來自 GitHub Action 的錯誤：

Run flutter pub get
......
Resolving dependencies...
The current Dart SDK version is 3.4.3.
Because what_for_meal requires SDK version ^3.7.0, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.32.2. 
Error: Process completed with exit code 1.