fix: 讓工作流中指定的 Dart SDK 版本與本地一致
來自 GitHub Action 的錯誤：

Run flutter pub get
.....
Resolving dependencies...
Note: intl is pinned to version 0.20.2 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.
Because no versions of firebase_ui_auth match >1.16.1 <2.0.0 and firebase_ui_auth 1.16.1 depends on flutter_localizations from sdk, firebase_ui_auth ^1.16.1 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.20.2, firebase_ui_auth ^1.16.1 requires intl 0.20.2.
So, because what_for_meal depends on both firebase_ui_auth ^1.16.1 and intl ^0.19.0, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.20.2
Failed to update packages.
Error: Process completed with exit code 1.